### Environment Variables
@baseUrl = http://localhost:4004/api/v1

### Get all Bonus Tranches
GET {{baseUrl}}/BonusTranche
Authorization: Basic <YOUR_AUTH_TOKEN>

### Get a specific BonusTranche by ID
GET {{baseUrl}}/BonusTranche/52ab4457-d716-450a-b8dc-e9104114fe34
Authorization: Basic <YOUR_AUTH_TOKEN>

### Delete a specific Bonus Tranche by ID
DELETE {{baseUrl}}/BonusTranche/52ab4457-d716-450a-b8dc-e9104114fe34
Authorization: Basic <YOUR_AUTH_TOKEN>

### Create a Bonus Tranche
POST {{baseUrl}}/BonusTranche
Content-Type: application/json
Authorization: Basic <YOUR_AUTH_TOKEN>

{
    "Location_ID": "2f5d3f93-0c3f-437d-9d8d-8ad9a4e84f7d",
    "name": "Quater 1 for 2024",
    "beginDate": "2024-04-01T00:00:00Z",
    "endDate": "2024-03-31T00:00:00Z",
    "dateOfOrigin": "2024-03-31T00:00:00Z",
    "trancheWeight": 50,
    "Target": [
        {
            "name": "Sales Target",
            "weight": 60,
            "achievement": 75.5
        },
        {
            "name": "Customer Satisfaction",
            "weight": 40,
            "achievement": 90
        }
    ]
}

### EditContent for a Bonus Tranche
POST {{baseUrl}}/updateBonusTranche
Content-Type: application/json
Authorization: Basic <YOUR_AUTH_TOKEN>

{    
    "bonusTrancheId": "52ab4457-d716-450a-b8dc-e9104114fe34",
    "Location_ID": "2f5d3f93-0c3f-437d-9d8d-8ad9a4e84f7d",
    "name": "Quater twenty",
    "beginDate": "2024-03-01T00:00:00Z",
    "endDate": "2024-03-20T00:00:00Z",
    "dateOfOrigin": "2024-03-31T00:00:00Z",
    "trancheWeight": 50,
    "targets": [
        {
            "name": "Sales Target",
            "weight": 60,
            "achievement": 75.5
        },
        {
            "name": "Customer Satisfaction",
            "weight": 40,
            "achievement": 90
        }
    ]
}

### Get all Bonus Tranches participations
GET {{baseUrl}}/TrancheParticipation?$expand=participant($expand=department),bonusTranche($expand=Location)
# Authorization: Basic <YOUR_AUTH_TOKEN>

### Exclude selected participants
POST {{baseUrl}}/excludeParticipants
Content-Type: application/json
# Authorization: Basic <YOUR_AUTH_TOKEN>

{
    "trancheParticipationIds": [
        "660ed93c-6966-4c42-b7a5-2aa2c0058a7a",
        "0a1bdfda-b42a-4628-8692-f8327bc9de41"
    ],
    "justification": "Mandatory justification"
}
